# configure image with python
# test the 2 servers that run on nginx

FROM python:latest

RUN pip install requests

RUN mkdir /app /result

COPY ./test_app /app/

CMD ["python", "/app/test_app.py"]
